---
- name: Launch EC2 instances
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch EC2 instances with public IP
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: ansible
        instance_type: t2.micro
        image_id: "{{ item.image }}"
        region: ap-south-1
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        network_interfaces:
          - device_index: 0
            subnet_id: subnet-05d3f3e13f2e920f8
            groups:
              - sg-0593269c4861ea671
            associate_public_ip_address: yes
        tags:
          environment: "{{ item.name }}"
      loop:
        - { image: ami-0dee22c13ea7a9a67, name: manage-node-1 }
        - { image: ami-0dee22c13ea7a9a67, name: manage-node-2 }
        - { image: ami-0144277607031eca2, name: manage-node-3 }
